name: stimulus
channels:
  - brian-team
  - anaconda
  - defaults
dependencies:
  - brian2=2.2.1=py27h2d50403_0
  - future=0.17.1=py27_0
  - futures=3.2.0=py27_0
  - h5py=2.8.0
  - ipykernel=4.10.0=py27_0
  - ipython=5.8.0=py27_0
  - joblib=0.13.2=py27_0  
  - jupyter=1.0.0=py27_7
  - matplotlib=2.2.3
  - notebook=5.7.4=py27_0
  - numba=0.41.0
  - pillow=5.3.0  
  - pip=18.1=py27_0  
  - python=2.7.15
  - tqdm=4.28.1=py27h28b3542_0
  - pip:
    - numpy==1.16.1
    - pandas==0.18.1
    - pypet==0.3.0
    - scipy==1.2.1
    - yapf==0.27.0
